development:
  adapter: postgresql
  encoding: unicode
  database: crime_reporting_system_test2
  username: saigaikwadd
  password: sahil
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
